name: finance_assistent
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: ^1.0.8
  pinput: ^5.0.2
  smooth_page_indicator: ^2.0.1
  percent_indicator: ^4.2.5



  # Navigation
  go_router: ^15.1.1

  # overlay
  fluttertoast: ^9.0.0

  # Local Storage
  shared_preferences: ^2.5.2

  # services
  dio: ^5.8.0+1
  image_picker: ^1.1.2

  # Assets
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1

  # Classes & Functions
  dart_mappable: ^4.4.0
  form_builder_validators: ^11.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # splash & icons
  flutter_native_splash: ^2.4.1

  # Navigation
  go_router_builder: ^4.1.3
  build_verify: ^3.1.1
  build_runner: ^2.10.4


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 900